<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\RusK.props" />

  <PropertyGroup>
    <AssemblyName>RuskPartyFormation</AssemblyName>
    <RootNamespace>RusK.Mods.Formation</RootNamespace>
    <Version>1.0.0</Version>
    <DeployDir>$(RuskGameDir)\mods</DeployDir>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="$(InteropDir)\Assembly-CSharp.dll" Private="false" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RusK.API\RusK.API.csproj" Private="false" />
  </ItemGroup>
</Project>
