<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\RusK.props" />

  <PropertyGroup>
    <AssemblyName>RusK.API</AssemblyName>
    <RootNamespace>RusK.API</RootNamespace>
    <Version>1.2.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="RusK.Core" />
  </ItemGroup>
</Project>
