<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\RusK.props" />

  <PropertyGroup>
    <AssemblyName>RusK.Core</AssemblyName>
    <RootNamespace>RusK.Core</RootNamespace>
    <Version>1.1.5</Version>
    <DeployDir>$(BepInExDir)\plugins\RusK</DeployDir>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="$(BepInExDir)\core\BepInEx.Core.dll" Private="false" />
    <Reference Include="$(BepInExDir)\core\BepInEx.Unity.IL2CPP.dll" Private="false" />
    <Reference Include="$(BepInExDir)\core\BepInEx.Unity.Common.dll" Private="false" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RusK.API\RusK.API.csproj" />
  </ItemGroup>

  <!-- RusK.API.dll も plugins/RusK に一緒に置く -->
  <ItemGroup>
    <RuskExtraDeploy Include="$(OutputPath)RusK.API.dll" />
  </ItemGroup>
</Project>
